import { SimulationClock } from "../src/core/clock/index.ts";
import { CommandDispatcher } from "../src/core/commands/index.ts";
import { EconomyLoop } from "../src/simulation/economy/loop.ts";
import type { HouseholdCohort } from "../src/simulation/households/index.ts";
import type { CityState, District } from "../src/simulation/models.ts";
import { UtilitiesLoop } from "../src/simulation/utilities/index.ts";
import { SocialRiskLoop } from "../src/simulation/social-risk/index.ts";
import { OrganizationsLoop } from "../src/simulation/organizations/index.ts";
import { OpinionLoop, channelDelta } from "../src/simulation/opinion/index.ts";

const district = (id: string): District => ({ id, population: 0, approval: 0.6, services: { water: { capacity: 10000, demand: 0, coverage: 1, maintenance: 1 }, electricity: { capacity: 10000, demand: 0, coverage: 1, maintenance: 1 }, waste: 1, safety: 1, internet: 1 }, economy: { employment: 1, averageIncome: 0, costOfLiving: 500 }, social: { inequality: 0.3, trust: 0.6, institutionalTrust: 0.6, unrest: 0, crimeRisk: 0, atRisk: false } });
const cohort = (income: number, size: number): HouseholdCohort => ({ size, income, savings: 2000, debt: 500, education: 0.6, unemployment: 0.08, needs: { monthlyCost: 500, satisfaction: 0.9, waterDemand: 4, electricityDemand: 3 }, politicalLean: 0, trust: 0.6, stress: 0.1 });
const city: CityState = { treasury: 2000000, debt: 0, approval: 0.6, taxRate: 0.15, auditLevel: 0.8, corruptionRisk: 0, organizations: [], districts: [district("north"), district("center"), district("south")] };
const cohorts = { north: [cohort(1800, 400), cohort(3200, 250)], center: [cohort(2400, 500), cohort(5000, 150)], south: [cohort(1400, 600), cohort(2800, 300)] };
cohorts.north.forEach(item => { item.needs.monthlyCost = 20; });
const clock = new SimulationClock({ millisecondsPerSimulatedDay: 10 }); clock.setSpeed(100);
const dispatcher = new CommandDispatcher(); const utilities = new UtilitiesLoop(city, cohorts, clock, dispatcher); const loop = new EconomyLoop(city, cohorts, clock, dispatcher, id => utilities.coverage(id)); const risk = new SocialRiskLoop(city, cohorts, clock, dispatcher); const organizations = new OrganizationsLoop(city, cohorts, clock, dispatcher); const opinion = new OpinionLoop(city, cohorts, clock, dispatcher);
const report = (label: string) => { console.log(label); for (const d of city.districts) console.log(`  ${d.id}: approval=${d.approval.toFixed(2)} crimeRisk=${d.social.crimeRisk.toFixed(2)} atRisk=${d.social.atRisk} employment=${d.economy.employment.toFixed(2)} income=${d.economy.averageIncome.toFixed(0)}`); for (const org of city.organizations) console.log(`  org=${org.type} income=${org.income.toFixed(0)} influence=${org.influence.toFixed(2)} territory=${org.territory.join(",")}`); console.log(`  footprints=${opinion.footprints.length} cityApproval=${city.approval.toFixed(2)} corruptionRisk=${city.corruptionRisk.toFixed(2)} audit=${city.auditLevel.toFixed(2)}`); };
clock.onMonthlyTick(tick => { if (tick.dayOfYear === 1 || tick.dayOfYear === 183) report(`year ${tick.year} day ${tick.day}`); });
clock.advance((7 * 10) / 100); report("healthy capacity");
clock.advance((365 * 2 * 10) / 100);
cohorts.north.forEach(cohort => { cohort.unemployment = 0.96; }); city.districts.find(d => d.id === "north")!.social.institutionalTrust = 0;
clock.advance((7 * 10) / 100); report("north neglected");
const crimeFootprint = opinion.footprints.find(item => item.topic === "crime")!;
console.log(`  wordOfMouth delta: north=${channelDelta(crimeFootprint, "wordOfMouth", "north", 2).toFixed(3)} center=${channelDelta(crimeFootprint, "wordOfMouth", "center", 2).toFixed(3)} south=${channelDelta(crimeFootprint, "wordOfMouth", "south", 2).toFixed(3)}`);
dispatcher.dispatch({ type: "HOLD_PRESS_CONFERENCE", topic: "crime", message: "acknowledge" });
report("press acknowledge");
dispatcher.dispatch({ type: "HOLD_PRESS_CONFERENCE", topic: "crime", message: "deny" });
report("press deny");
dispatcher.dispatch({ type: "INVEST_SOCIAL_PROGRAM", district: "north", amount: 50000 });
clock.advance((7 * 10) / 100); report("north social program 1");
dispatcher.dispatch({ type: "INVEST_SOCIAL_PROGRAM", district: "north", amount: 50000 });
clock.advance((7 * 10) / 100); report("north social program 2");
dispatcher.dispatch({ type: "INVEST_SOCIAL_PROGRAM", district: "north", amount: 50000 });
clock.advance((7 * 10) / 100); report("north social program 3");
dispatcher.dispatch({ type: "SET_AUDIT_LEVEL", value: 0 });
clock.advance((7 * 10) / 100); report("audit lowered");
dispatcher.dispatch({ type: "SET_AUDIT_LEVEL", value: 0.9 });
clock.advance((7 * 10) / 100); report("audit increased");
utilities.setCapacity("north", "water", 400); utilities.setCapacity("north", "electricity", 400);
clock.advance((14 * 10) / 100); report("north capacity reduced");
clock.advance((365 * 3 * 10) / 100); report("after 5 years");
