import { gridToIso, ISO_TILE_H, ISO_TILE_W } from '../isoMath.ts';
import type { Projection } from '../projection.ts';
import { buildRoadGraph, findRoadRoute, roadSignature, type RoadGraph } from '../trafficSystem.ts';
import { destinationScreenPoint } from './destination.ts';
import { activityInfo } from './activity.ts';
import { commuteDelayState } from './commuteDelay.ts';
type RoutineBlock = { activity: string; startHour: number; endHour: number; location: 'home' | 'work' | 'commercial' | 'refuel' };
type Tile = { type?: string } | null; type Point = { col: number; row: number };
type Citizen = { id: string; householdId?: string; level: number; homeTile?: Point; workTile?: Point; commercialTile?: Point; refuelTile?: Point; routine?: RoutineBlock[] };
type Trip = { id: string; route: Point[]; target: Point; progress: number; activityKey: string };
function key(p: Point) { return `${p.col},${p.row}`; }
function nearestRoad(graph: RoadGraph, p: Point, exclude?: Point) { return [...graph.keys()].map(v => { const [col, row] = v.split(',').map(Number); return { col, row }; }).filter(v => !exclude || key(v) !== key(exclude)).sort((a, b) => Math.abs(a.col - p.col) + Math.abs(a.row - p.row) - Math.abs(b.col - p.col) - Math.abs(b.row - p.row))[0]; }
export function createCitizenTransit() {
  let graphSignatureValue = '', rosterSignature = '', activitySignature = '', lastTime = 0, syncedDay: number | undefined, syncedHour: number | undefined; let graph: RoadGraph = new Map();
  const trips = new Map<string, Trip>(), positions = new Map<string, { cx: number; cy: number }>(), sent = new Set<string>();
  const currentActivity = (c: Citizen, hour: number) => c.routine?.find(b => hour >= b.startHour && hour < b.endHour);
  const rebuild = (map: Tile[][], citizens: Citizen[], day: number, hour: number, preserve: boolean) => { const oldTrips = new Map(trips); graph = buildRoadGraph(map); graphSignatureValue = roadSignature(map); const next = new Map<string, Trip>(); for (const c of citizens.filter(v => v.level === 3 && v.homeTile && v.workTile)) { const a = currentActivity(c, hour), activityKey = `${day}:${a?.startHour ?? -1}:${a?.endHour ?? -1}:${a?.activity ?? 'commute'}`, old = preserve ? oldTrips.get(c.id) : undefined; const target = a?.location === 'home' ? c.homeTile! : a?.location === 'commercial' ? (c.commercialTile ?? c.workTile!) : a?.location === 'refuel' ? (c.refuelTile ?? c.workTile!) : c.workTile!; const from = old && old.route.length ? nearestRoad(graph, old.route[Math.min(old.route.length - 1, Math.floor(old.progress * (old.route.length - 1)))]) : nearestRoad(graph, target === c.homeTile ? c.workTile! : c.homeTile!); const to = nearestRoad(graph, target, from); if (!from || !to) { next.set(c.id, { id: c.id, route: [], target, progress: 1, activityKey }); continue; } let route = findRoadRoute(graph, from, to); if (!route.length && key(from) !== key(to)) route = [from, to]; if (route.length) next.set(c.id, { id: c.id, route, target, progress: route.length === 1 ? 1 : old?.activityKey === activityKey ? old.progress : 0, activityKey }); } trips.clear(); for (const [id, trip] of next) trips.set(id, trip); };
  return { syncState(day: number, hour: number) { syncedDay = day; syncedHour = hour; }, updateAndDraw(ctx: CanvasRenderingContext2D, time: number, ox: number, oy: number, zoom: number, map: Tile[][], citizens: Citizen[], day: number, hour = 0, simulationSpeed = 1, render = true, project?: Projection, selectedCitizenId?: string, postCommand?: (command: Record<string, unknown>) => Promise<unknown>) {
    day = syncedDay ?? day; hour = syncedHour ?? hour; const active = citizens.filter(c => c.level === 3); const roster = active.map(c => `${c.id}:${c.homeTile?.col},${c.homeTile?.row}:${c.workTile?.col},${c.workTile?.row}`).join('|'); const activities = `${day}|${active.map(c => { const a = currentActivity(c, hour); return `${c.id}:${a?.startHour ?? -1}:${a?.endHour ?? -1}:${a?.activity ?? 'commute'}`; }).join('|')}`; if (roadSignature(map) !== graphSignatureValue || roster !== rosterSignature || activities !== activitySignature) { rebuild(map, citizens, day, hour, roster === rosterSignature); rosterSignature = roster; activitySignature = activities; } const dt = lastTime ? Math.min(.05, (time - lastTime) / 1000) * simulationSpeed : 0; lastTime = time;
    for (const trip of trips.values()) { const wasArrived = trip.progress >= 1; trip.progress = Math.min(1, trip.progress + dt / 8); const citizen = citizens.find(c => c.id === trip.id); const a = citizen ? currentActivity(citizen, hour) : undefined; if (!wasArrived && trip.progress >= 1 && (a?.activity === 'compras' || a?.activity === 'refuel') && postCommand && citizen?.householdId) { const marker = `${citizen.id}:${a.activity}:${day}`; if (!sent.has(marker)) { sent.add(marker); void postCommand({ type: 'CITIZEN_CONSUMPTION', cohortId: citizen.householdId, districtId: (citizen as any).districtId, activity: a.activity === 'compras' ? 'shop' : 'refuel', day }); } } const routePosition = trip.progress * (trip.route.length - 1), segment = Math.min(trip.route.length - 2, Math.floor(routePosition)), local = routePosition - segment, from = trip.route[segment], to = trip.route[segment + 1]; const destination = trip.progress >= 1 && project ? destinationScreenPoint(trip.id, trip.target, project, zoom) : undefined; const roadPoint = from && to ? project ? project(from.col + (to.col - from.col) * local, from.row + (to.row - from.row) * local) : (() => { const iso = gridToIso(from.col + (to.col - from.col) * local, from.row + (to.row - from.row) * local); return { x: iso.x * zoom + ox, y: iso.y * zoom + oy }; })() : undefined; const cx = destination?.x ?? (roadPoint ? roadPoint.x + ISO_TILE_W * zoom / 2 : 0), cy = destination?.y ?? (roadPoint ? roadPoint.y + ISO_TILE_H * zoom / 2 : 0); positions.set(trip.id, { cx, cy }); if (!render) continue; const visual = activityInfo(a); ctx.save(); ctx.translate(cx, cy - 6 * zoom); if (trip.id === selectedCitizenId) { ctx.beginPath(); ctx.arc(0, 0, Math.max(15, 20 * zoom), 0, Math.PI * 2); ctx.strokeStyle = '#fff3a3'; ctx.lineWidth = Math.max(2, 3 * zoom); ctx.shadowColor = '#ffd166'; ctx.shadowBlur = 10 * zoom; ctx.stroke(); } const w = Math.max(7, 13 * zoom), h = Math.max(4, 7 * zoom); ctx.fillStyle = '#17202a'; ctx.fillRect(-w, -h, w * 2, h * 2); ctx.fillStyle = '#f5c542'; ctx.fillRect(-w * .86, -h * .82, w * 1.72, h * 1.64); ctx.fillStyle = '#25b7a7'; ctx.fillRect(-w * .36, -h * .58, w * .72, h * 1.16); ctx.fillStyle = visual.color; ctx.font = `${Math.max(10, 13 * zoom)}px sans-serif`; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillText(visual.icon, w * 1.25, -h * 1.4); ctx.restore(); }
  }, getCitizenAt(x: number, y: number, citizens: Citizen[]) { let closest: Citizen | undefined, distance = 24; for (const c of citizens) { const p = positions.get(c.id); if (!p) continue; const d = Math.hypot(p.cx - x, p.cy - y); if (d < distance) { distance = d; closest = c; } } return closest; }, getCitizenTripProgress(id: string) { return trips.get(id)?.progress; }, getCommuteDelayState(citizen: Citizen) { const trip = trips.get(citizen.id); return commuteDelayState(citizen.level, citizen.homeTile, citizen.workTile, trip?.route.length); } };
}
